### ISSUE TITLE
Mailchimp list is not updated automatically for new members

### ISSUE THREAD

**Issue by katrinafyi** [UQComputingSociety/signup#33]
It works when testing initially so maybe it only breaks after running for a period of time. 

I suspect an unhandled exception is killing the Mailchimp worker. It could be related to this SQLAlchemy error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/signup/lib/python3.6/site-packages/uqcs/workers.py", line 52, in mailchimp_worker
    data['merge_fields']['SNUM'] = item.student_no
  File "/srv/signup/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/srv/signup/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
    value = state._load_expired(state, passive)
  File "/srv/signup/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/srv/signup/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 915, in load_scalar_attributes
    "attribute refresh operation cannot proceed" % (state_str(state))
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Student at 0x7fffe9d32be0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
```

**Comment by nicklambourne** [comment]
It is. The ORM object is expiring in between form submission and worker operation. I think passing the generated ID (after the entry is committed to the DB) to the worker and letting the worker re-request the object in a new session (using that ID - which is just an int) is how we can fix this.

**Comment by katrinafyi** [comment]
That could work, but why would it be expiring? I'd imagine the worker processes incoming items almost instantly.

**Comment by nicklambourne** [comment]
Yes, but it's not the same session. The instances are attached to the session they were created in.

**Comment by katrinafyi** [comment]
#34 did not adequately fix the issue, most likely because the fields are not populated before being expunged.
